# Tasks
Solutions to Ian McLoughlin's Tasks assessment, by Fintan Hegarty (fintan.hegarty@gmail.com) 
***

## Task 1

#### Calculate the square root of 2 to 100 decimal places

In Example 1.1, we give a toy example. Approaches 1.2 and 1.4 fail due to insufficient computing power and precision. Approach 1.5 uses the digit-by-digit method and works. Testing 1.3 grabs the correct value for $\sqrt{2}$ from both the sympy module and a website. Comparison 1.6 checks that our answer from Approach 1.5 is correct. 

[Final Answer](#sqrt-FA) is the function to compute and print the square root of two to 100 decimal places, and its execution.


#### Example 1.1 Calculate the square root of 2 to ten decimal places 

We can calculate the square root of a number using Newton's method [<sup>1,</sup>](#sqrt-on-on)[<sup>2</sup>](#sqrt-on-tw).
To find the square root $z$ of a number $x$, we iterate using the following formula, until a satisfactory error bound is met:

$$ z_{i+1} = z_i-\frac{z_i^2-x}{2z_i} $$


In [1]:
def newton_sqrt(x):
    """
    A function to calculate the square root of a number x
    """
    # initial guess for sqrt z
    z=x/2
    # loop until satisfactory guess
    while abs(x - z*z) >0.0000000001 :
        # make a better guess
        z -= (z*z - x)/(2*z)
    # return sufficiently close approximation to sqrt x.
    # return ('{0:.10f}'.format(z))
    return (round(z,10))    

We test the function with some known values

In [2]:
# Test the function on 100
newton_sqrt(100)

10.0

In [3]:
# Test the function on 36
newton_sqrt(36)

6.0

In [4]:
# Test the function on 2
newton_sqrt(2)

1.4142135624

In [5]:
# Compare with numpy's sqrt function
# (This does necessitate an import, which is presumably fine.)
import numpy as np
numpy_sqrttwo_value = np.sqrt(2)
print("numpy's value is\n",'{0:.16f}'.format(numpy_sqrttwo_value))
print("newton_sqrt's value is\n", newton_sqrt(2))

if float(numpy_sqrttwo_value) == float(newton_sqrt(2)):
    print("They are the same.")
else:
    print("They are different.")
    

numpy's value is
 1.4142135623730951
newton_sqrt's value is
 1.4142135624
They are different.


This is not wholly surprising, and in any event, we're just comparing the printed values, as opposed to the actual value of the numbers we are describing. Using round instead:

In [6]:
# Compare with numpy's sqrt function using round
import numpy as np
numpy_sqrttwo_value_rounded = round(np.sqrt(2),10)
newton_sqrttwo_rounded = round(newton_sqrt(2),10)
print("numpy's value is\n", numpy_sqrttwo_value_rounded)
print("newton_sqrt's value is\n", round(newton_sqrt(2),10))

if numpy_sqrttwo_value_rounded==newton_sqrttwo_rounded:
    print("They are the same.")
else:
    print("They are different.")


numpy's value is
 1.4142135624
newton_sqrt's value is
 1.4142135624
They are the same.


#### Attempt 1.2

The method used in Example 1.1 will not work for the square root of 100, as the computer can't handle it. Therefore we try a version of the Babylonian method, borrowed from Wikipedia[<sup>3</sup>](#sqrt-on-th)

The formula here is

$$ a_{i+1} = \frac{a_i}{2}+\frac{1}{i} $$

In [7]:
def bab_sqrt(x):
    """
    A function to calculate the square root of a number x, hopefully more efficiently
    than the Newton method.
    """
    # initial guess for sqrt z
    a=1
    for i in range(1,100):
    # loop until satisfactory guess
        while abs(x - a*a) >0.000000000000001 :
        # make a better guess
            a = (a/2)+(1/a)
    # return sufficiently close approximation to sqrt x.
    return ('{0:.100f}'.format(a))
    # print(float("{0:.100f}".format(a)))
    # print(round(a,100))

In [8]:
bab_sqrt(2)

'1.4142135623730949234300169337075203657150268554687500000000000000000000000000000000000000000000000000'

These digits appear to be inaccurate (visually - though we compare below so we have the method for when it is less obvious) according to the NASA website[<sup>4</sup>](#sqrt-on-fo) listing of the number (or the value from sympy, as given below), and equally problematically, a load of zeros are being uselessly printed instead of the actual digits. However, the method appears to be sufficiently fast that it actually runs, so that's a plus.

#### Testing 1.3
We grab the value of the square root of 2 from nasa.gov [<sup>4</sup>](#sqrt-on-fo) (and also using sqrt from sympy), for a comparison with the value we get, to confirm its accuracy.

In [9]:
# (This does necessitate imports for grabbing data and regexing, which is presumably fine,
#   as we are only using it for comparison, as opposed to calculating.)
import requests
import re
# Grab page content as string
page = requests.get("https://apod.nasa.gov/htmltest/gifcity/sqrt2.1mil").text

# Get rid of newlines
page = page.replace("\n","")

# Search for string beginning with 1.4 and grab the following 99 digits
# group(0) just takes the actual string as opposed to the object
real_sqrttwo_value = re.search("1.4\d{99}", page).group(0)
print("The correct value of square root two to 100 places is\n", real_sqrttwo_value)

The correct value of square root two to 100 places is
 1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


In [10]:
# Again, this import is just for comparison.
from sympy import sqrt
sympy_sqrttwo_value=sqrt(2).evalf(101)
print(sympy_sqrttwo_value)

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


In [11]:
if round(float(bab_sqrt(2)),100)==round(float(real_sqrttwo_value),100):
    print ("They are the same.")
else:
    print ("They are different.")
    
if round(float(sympy_sqrttwo_value),100)==round(float(real_sqrttwo_value),100):
    print ("They are the same.")
else:
    print ("They are different.")
    

They are different.
They are the same.


#### Approach 1.4

The decimal precision appears problematic. Perhaps we can calculate the same number to some power of 10, to give the correct digits, with only the decimal point misplaced?
If $n=\sqrt{2}$, then $10n=\sqrt{100\times 2}$, so to calculate $n$ we can calculate $\sqrt{100\times 2}$ and move the decimal point one place to the right.

In [12]:
n=newton_sqrt(2)
print('n is ',n)
f=newton_sqrt(100*2)
print('n is ',f,' with the decimal to be moved one space to the right.')

n is  1.4142135624
n is  14.1421356237  with the decimal to be moved one space to the right.


Let $n=\sqrt{2}$. Let $f$ (the 'fake' evaluation, whose decimal point we will move) be $10^{100}$ times bigger than $\sqrt{2}$ (so the decimal point will be 100 places to the left of where we want it). So the number under the square root sign will be $ 10^{200}$ times bigger than $2$; i.e., $f=\sqrt{2\times10^{200}}$, and then we will move the decimal point 100 places to the right.


In [13]:
f = 2*10**(4) 
answer = format(newton_sqrt(f), ',.100f') 
print(answer)

141.4213562372999888339109020307660102844238281250000000000000000000000000000000000000000000000000000000


This appears to be on the right track, but the newton_sqrt method is struggling for bigger powers, so a different approach to newton_sqrt may be required.

#### Approach 1.5
We will try the digit-by-digit approach of calculating the square root, as detailed, for example on Wikipedia.[<sup>5</sup>](#sqrt-on-fi)
Though the idea used here is largely the same as there, we can take some short-cuts; e.g., we know we start with 2, and that all we will add to the right-hand side will be pairs of zeros.

In [14]:
# Initialise values
# I've used c and r where only c is mentioned on wikipedia, but they're just different stages of the same thing.
c=2; x=0; y=0; r=0; A=0; p=0;

# Handling the first iteration separately makes the loop less complicated to write
while (x+1)*(20*p+(x+1))<=2:
    x=x+1
y=x*(20*p+x)
r=c-y
A=x

# This is simpler than the example on the wiki, because we know we are only appending
# 00s, so no need for dividing up part of a string and grabbing two pieces, etc.
# We do end up with a number 10^100 times bigger than what we want, because we've
# ignored the decimals, but I'll stick that in afterwards.
for i in range(1,101):
    c=100*r; x=0; y=0; p=A;
    while (x+1)*((20*p)+(x+1))<=c:
        x=x+1
    y=x*(20*p+x)
    r=c-y
    # This serves the purpose of appending x to A
    A=A*10+x
print(A)

14142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


In [15]:
Ans=format(A/(10**100), ',.100f')
print(Ans)

1.4142135623730951454746218587388284504413604736328125000000000000000000000000000000000000000000000000


I guess we'll have to preserve it as a string, and just insert the decimal point.

In [16]:
# Sticking in the decimal
stringA=str(A)
Ans=stringA[:1] + '.' + stringA[1:]
print(Ans)

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


#### Comparison 1.6
We compare the string with actual values acquired from sympy and nasa website to confirm accuracy. (Also with the incorrect (excessively rounded) value from numpy as a control. 

In [17]:
# Testing by comparing strings
print(Ans==str(sympy_sqrttwo_value))
print(Ans==str(numpy_sqrttwo_value))
print(Ans==str(real_sqrttwo_value))

True
False
True


#### Answer 1.7

In [18]:
print("The square root of 2, to 100 decimal places is\n",Ans)

The square root of 2, to 100 decimal places is
 1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727



#### <span id="sqrt-FA">FINAL ANSWER TO TASK 1:</span>

In [1]:
def sqrt2():
    c=2; x=0; y=0; r=0; A=0; p=0;
    while (x+1)*(20*p+(x+1))<=2:
        x=x+1
    y=x*(20*p+x)
    r=c-y
    A=x
    for i in range(1,101):
        c=100*r; x=0; y=0; p=A;
        while (x+1)*((20*p)+(x+1))<=c:
            x=x+1
        y=x*(20*p+x)
        r=c-y
        A=A*10+x
        stringA=str(A)
        Ans=stringA[:1] + '.' + stringA[1:]
    print(Ans)

In [2]:
sqrt2()

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


***

## Task 2
| |A|B|C|D|Total
| --- | --- | --- | --- | --- | --- |
| White collar|90|60|104|95|349 |
| Blue collar|30|50|51|20|151|
| No collar|30|40|45|35|150|
| Total|150|150|200|150|650|

#### Use scipy.stats  [<sup>8</sup>](#chi-tw-th) to verify the $\chi^{2}$ value [<sup>6</sup>](#chi-tw-on) of this table is 24.6, and calculate the associated $p$ value. [<sup>7</sup>](#chi-tw-tw)
    


In [21]:
import numpy as np
import pandas as pd
import scipy.stats as st

# First we create the data frame; there's no need to include the totals, as these will
# be calculated by python later
deets={'A': [90,30,30], 'B': [60,50,40], 'C': [104,51,45], 'D': [95,20,35]}
df = pd.DataFrame(data=deets)
df.index=["White collar", "Blue collar", "No collar"]
print(df,'\n')

# let scipy.stats do all the hard work, and assign the values
chi2, pv, dof, exp  = st.chi2_contingency(df)
print('The test statistic value is', chi2, '. \n')
print('The p value value is', pv, '. \n')
print('There are', dof, 'degrees of freedom. \n')
print('The expected value matrix if neighbourhood and collar were independent would be\n', exp, '.\n')

               A   B    C   D
White collar  90  60  104  95
Blue collar   30  50   51  20
No collar     30  40   45  35 

The test statistic value is 24.5712028585826 . 

The p value value is 0.0004098425861096696 . 

There are 6 degrees of freedom. 

The expected value matrix if neighbourhood and collar were independent would be
 [[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]] .



The p value here (0.00041) is very small, certainly smaller than any alpha level/threshold of significance we are likely to be asked to test for, so we may reject the null hypothesis; i.e., we cannot say that the collar colour and region are independent.

***
# Task 3

#### Describe and contrast Excel's STDEV.P and STDEV.S. Use numpy to perform a simulation demonstrating that STDEV.S is a better estimate for the standard deviation of a population when performed on a sample. 

The formula for the standard deviation [<sup>9</sup>](#std-th-on) of a population is
$$\sigma=\sqrt{\frac{\sum\limits_{i=1}^N(x_i-\mu)}{N}},$$
where $N$ is the size of the population and $\mu$ is the mean of the population.

This is calculated in Microsoft Excel [<sup>10</sup>](#std-th-tw) with the function STDEV.P.

Often, we do not have a full population, and only have a sample to calculate with. Intuitively, the expected values of the variance and deviation of a sample are greater than those of the population itself. (E.g., selecting 1000 random points from a normal distribution is likely to give a more accurate idea of the spread of the population's data than a sample of just 10 points, where adding one or two extra points could have a large effect on the expected variance and deviation of the sample. As the size of the sample approaches the size of the population, the variability of the values tends to the settle down.)

To reduce the value of the formula above, we increase the value of the denominator. 
This is a somewhat intuitive justification for the amended formula. The "intuitive" justification for changing the value of the denominator from $n$ to $n-1$ seems to really be either empirical or algebraic. Empirical support seems to be the latter part of the question, and an algebraic proof seems beyond the scope of the module, so I will refrain from copy and pasting it from, for example, Wikipedia's entry on Bessel's correction[<sup>11</sup>](#std-th-th). 

## References
<span id="sqrt-on-on"> 1. A Tour of Go: Loops and Functions https://tour.golang.org/flowcontrol/8</span>

<span id="sqrt-on-tw"> 2. Newton's method: https://en.wikipedia.org/wiki/Newton%27s_method</span>

<span id="sqrt-on-th"> 3. Babylonian method: https://en.wikipedia.org/wiki/Square_root_of_2</span>

<span id="sqrt-on-fo"> 4. Accurate square root of 2: https://apod.nasa.gov/htmltest/gifcity/sqrt2.1mil</span>

<span id="sqrt-on-fi"> 5. Digit-by-digit method of calculating square root: https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Digit-by-digit_calculation</span>

<span id="chi-tw-on"> 6. Chi-squared test: https://en.wikipedia.org/wiki/Chi-squared_test</span>

<span id="chi-tw-tw"> 7. p-value: https://www.simplypsychology.org/p-value.html</span>

<span id="chi-tw-th"> 8. scipy.stats manual: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html</span>

<span id="std-th-on"> 9. STDEV Microsoft https://support.microsoft.com/en-us/office/stdev-s-function-7d69cf97-0c1f-4acf-be27-f3e83904cc23</span>

<span id="std-th-tw"> 10. Standard deviation https://en.wikipedia.org/wiki/Standard_deviation</span>

<span id="std-th-th"> 11. Bessel's correction https://en.wikipedia.org/wiki/Bessel%27s_correction</span>


